import { ScriptData, ScriptDataTransformer } from "@lichtblick/suite-base/players/UserScriptPlayer/types";
import { Topic } from "@lichtblick/suite-base/players/types";
import { TransformArgs } from "./types";
export declare const hasTransformerErrors: (scriptData: ScriptData) => boolean;
export declare const getInputTopics: (scriptData: ScriptData) => ScriptData;
export declare const getOutputTopic: (scriptData: ScriptData) => ScriptData;
export declare const validateInputTopics: (scriptData: ScriptData, topics: Topic[]) => ScriptData;
export declare const compile: (scriptData: ScriptData) => ScriptData;
export declare const extractGlobalVariables: (scriptData: ScriptData) => ScriptData;
export declare const extractDatatypes: (scriptData: ScriptData) => ScriptData;
export declare const compose: (...transformers: ScriptDataTransformer[]) => ScriptDataTransformer;
declare const transform: (args: TransformArgs) => ScriptData;
export default transform;
