import { PropsWithChildren } from "react";
import { SidebarItem } from "@lichtblick/suite-base/components/Sidebars/types";
import "react-mosaic-component/react-mosaic-component.css";
type SidebarProps<OldLeftKey, LeftKey, RightKey> = PropsWithChildren<{
    items: Map<OldLeftKey, SidebarItem>;
    bottomItems: Map<OldLeftKey, SidebarItem>;
    selectedKey: OldLeftKey | undefined;
    onSelectKey: (key: OldLeftKey | undefined) => void;
    leftItems: Map<LeftKey, SidebarItem>;
    selectedLeftKey: LeftKey | undefined;
    onSelectLeftKey: (item: LeftKey | undefined) => void;
    leftSidebarSize: number | undefined;
    setLeftSidebarSize: (size: number | undefined) => void;
    rightItems: Map<RightKey, SidebarItem>;
    selectedRightKey: RightKey | undefined;
    onSelectRightKey: (item: RightKey | undefined) => void;
    rightSidebarSize: number | undefined;
    setRightSidebarSize: (size: number | undefined) => void;
}>;
export default function Sidebars<OldLeftKey extends string, LeftKey extends string, RightKey extends string>(props: SidebarProps<OldLeftKey, LeftKey, RightKey>): React.JSX.Element;
export {};
