/// <reference types="react" />
import { StoryObj, StoryContext, StoryFn } from "@storybook/react";
import LayoutBrowser from "./index";
declare function WithSetup(Child: StoryFn, ctx: StoryContext): React.JSX.Element;
declare const _default: {
    title: string;
    component: typeof LayoutBrowser;
    decorators: (typeof WithSetup)[];
};
export default _default;
export declare const Empty: StoryObj;
export declare const LayoutList: StoryObj;
export declare const MultiSelect: StoryObj;
export declare const MultiDelete: StoryObj;
export declare const MultiDuplicate: StoryObj;
export declare const MultiRevert: StoryObj;
export declare const MultiSave: StoryObj;
export declare const TruncatedLayoutName: StoryObj;
export declare const TruncatedLayoutNameSelected: StoryObj;
export declare const AddLayout: StoryObj;
export declare const MenuOpen: StoryObj;
export declare const MenuOpenLight: StoryObj;
export declare const EditingName: StoryObj;
export declare const CancelRenameWithEscape: StoryObj;
export declare const CommitRenameWithTab: StoryObj;
export declare const Duplicate: StoryObj;
export declare const DeleteLayout: StoryObj;
export declare const DeleteSelectedLayout: StoryObj;
export declare const DeleteLastLayout: StoryObj;
export declare const SignInPrompt: StoryObj;
