# Dependabotが作成したプルリクエストの自動修正ワークフロー
# yarn dedupeの自動実行とPRの自動承認を行う
#
# セキュリティ上重要: pull_request_targetイベントを使用
# 信頼されたコンテキストで実行されるため、スクリプト実行は無効化
#
# 参考:
# - https://github.com/dependabot/dependabot-core/issues/5830
# - https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
# - https://securitylab.github.com/research/github-actions-preventing-pwn-requests

name: Dependabot

on:
  - pull_request_target # セキュリティ対策のため

jobs:
  fix:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' # Dependabotのみ実行

    # セキュリティ上重要: スクリプト実行を無効化
    # 信頼されないPRが悪意のあるnpmパッケージを追加して
    # 信頼されたコンテキストで任意コードを実行するのを防ぐ
    env:
      YARN_ENABLE_SCRIPTS: false

    steps:
      # PRブランチのチェックアウト（専用トークン使用）
      # 新しいコミットでワークフローをトリガーするため専用トークンが必要
      - uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.LICHTBLICK_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      # Node.js 16.17 環境をセットアップ
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 16.17

      # Yarn パッケージマネージャーを有効化
      - run: corepack enable

      # 依存関係をインストール（スキップビルドモード）
      - run: yarn install --mode skip-build
        env:
          # CI環境のimmutableモードを無効化（更新許可のため）
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      # yarn dedupe実行（重複依存関係の解決）
      - run: yarn dedupe

      # 修正内容をコミット・プッシュ
      - name: Commit yarn.lock
        run: |
          git config user.name "dependabot[bot]"
          git config user.email "49699333+dependabot[bot]@users.noreply.github.com"
          git add -u
          git commit -m '[dependabot skip] Fix yarn.lock' --allow-empty
          git push

      # 新規作成PRの自動承認
      - uses: octokit/request-action@v2.4.0
        if: contains(fromJSON('["opened", "reopened"]'), github.event.action)
        env:
          GITHUB_TOKEN: ${{ secrets.LICHTBLICK_GITHUB_TOKEN }}
        with:
          route: POST /repos/{owner_and_repo}/pulls/{pull_number}/reviews
          owner_and_repo: ${{ github.repository }}
          pull_number: ${{ github.event.pull_request.number }}
          event: "APPROVE"

      # Dependabotに自動マージ指示コメント
      - uses: octokit/request-action@v2.4.0
        if: contains(fromJSON('["opened", "reopened"]'), github.event.action)
        env:
          GITHUB_TOKEN: ${{ secrets.LICHTBLICK_GITHUB_TOKEN }}
        with:
          route: POST /repos/{owner_and_repo}/issues/{pull_number}/comments
          owner_and_repo: ${{ github.repository }}
          pull_number: ${{ github.event.pull_request.number }}
          # シンタックスエラー回避のため二重引用符
          body: "'@dependabot squash and merge'"
